version: "3"
services:
  selenium-app:
    build: .
    depends_on:
      - chrome
    links:
      - chrome
    volumes:
      - ./your_selenium_project:/app
    environment:
      - DISPLAY=:99  # Necessary for running Chrome inside the container
    networks:
      - selenium_net

  chrome:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm  # For running Chrome without sandboxing
    networks:
      - selenium_net

networks:
  selenium_net:
